---
- name: add noc user
  user: name=noc

- name: make .ssh dir for user noc
  file:
    state: directory
    path: /home/noc/.ssh
    mode: 0600
    owner: noc
    group: noc

- name: copy authorized_keys
  copy:
    src: authorized_keys
    dest: /home/noc/.ssh/
    mode: 0600
    owner: noc
    group: noc
...
